stages:          # List of stages for jobs, and their order of execution
  - lint
  - build
  - test
  - deploy

lint-job: # This job runs in the first stage.
  stage: lint
  script:
    - uvx ruff check
    - uvx ruff format

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ...

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - ...

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - ...
