repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-format
        priority: 0
      - id: ruff-check
        args: [ --fix, --exit-non-zero-on-fix ]
        types_or: [ python, pyi ]
        require_serial: true
        priority: 1
    