services:
  app:
    build:
      context: .
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
      - ./backend/certs:/app/certs
    env_file: .env
    command: >
      sh -c "uvicorn main:main_app --host 0.0.0.0 --port 8002 --reload"
    depends_on:
      - db
      - db_test

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5437:5432"
    restart: on-failure

  db_test:
    image: postgres:latest
    restart: on-failure
    volumes:
      - db_test:/var/lib/postgresql
    env_file:
    - .env.test
    ports:
      - "5433:5432"
volumes:
    db_test: