server {
    listen 80;
    server_name localhost;

    error_page 401 /error_401.html;

    location = /error_401.html {
        root /usr/share/nginx/error_html;
        internal;
    }

    location /docs {
        proxy_pass http://app:8002;
        proxy_set_header Host $host;
    }

    location /openapi.json {
        proxy_pass http://app:8002;
        proxy_set_header Host $host;
    }

    location / {
        if ($http_authorization = "") {
            return 401;
        }

        if ($http_authorization !~ "^Bearer ") {
            return 401;
        }

        proxy_pass http://app:8002;
        proxy_set_header Host $host;
    }
}